[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
commands = [
  "corepack enable",
  "corepack prepare yarn@4.6.0 --activate",
  "yarn install"
]

[phases.build]
commands = [
  "yarn build"
]

[start]
cmd = "yarn start"

