[phases.setup]
commands = [
  "corepack enable",
  "corepack prepare yarn@4.6.0 --activate"
]

[phases.install]
commands = [
  "yarn install --immutable"
]

[phases.build]
commands = [
  "yarn build"
]

[start]
cmd = "npm run start"
